language: python

python: "3.6"

cache: pip

sudo: required

services: docker

before_install: pip install flake8

# handled in the Docker image
install: true

before_script: flake8 -v .

script:
 - docker build -t tdmproject/tdm-tools .
 - docker run --rm tdmproject/tdm-tools bash -c "test/run"

deploy:
  - provider: script
    script: ./docker_push
    on:
      branch: develop
  - provider: pypi
    user: "${TDM_USER}"
    password: "${TDM_PASS}"
    on:
      tags: true
